#%RAML 1.0 ResourceType
usage: Apply this resource type to any resource that returns only a single item.
description: Operations performed on a single HMIS <<resourcePathName|!singularize>> within the system.
uriParameters:
  <<resourcePathName|!singularize>>id:
    example: ADBC1111211111114111111111D1111V
    type: string
    displayName: <<resourcePathName|!singularize|!uppercamelcase>> Identifier

get:
  description: Gets a <<resourcePathName|!singularize>> using a URI resource parameter/ID.
  responses:
    200:
      description: OK – Everything is working.
      body:
        application/json:
          type: <<schema_id>>
          example: <<schema_id_example>>
    400:
      description: Bad Request – The request was invalid or cannot be served.
    401:
      description: Unauthorized – The request requires an user authentication.
    403:
      description: 'Forbidden – The server understood the request, but is refusing it or the access is not allowed.'
    404:
      description: Not found – There is no resource behind the URI.
    500:
      description: Internal Server Error
put:
  description: Updates a specific <<resourcePathName|!singularize>> specified by the URI resource parameter/ID.
  body:
    application/json:
      type: <<schema>>
      example: <<schema_example>>
  responses:
    200:
      description: OK – Everything is working.
    304:
      description: Not Modified – The client can use cached data.
    400:
      description: Bad Request – The request was invalid or cannot be served.
    401:
      description: Unauthorized – The request requires a user.
    403:
      description: 'Forbidden – The server understood the request, but is refusing it or the access is not allowed.'
    404:
      description: Not found – There is no resource behind the URI.
    500:
      description: Internal Server Error.
delete:
  description: Deletes a specific <<resourcePathName|!singularize>> specified by the URI resource parameter/ID.
  responses:
    204:
      description: OK – The resource was successfully deleted.
    400:
      description: Bad Request – The request was invalid or cannot be served.
    401:
      description: Unauthorized – The request requires user authentication.
    403:
      description: 'Forbidden – The server understood the request, but is refusing it or the access is not allowed.'
    404:
      description: Not found – There is no resource behind the URI.
    500:
      description: Internal Server Error.
