
#%RAML 1.0
title: 2015 HMIS API
version: 1.1.1
mediaType: application/json
protocols:
  - HTTPS
baseUri: 'https://www.hmislynk.com/hmis-clientapi-v2015/rest/v2015'
securedBy: [oauth_2_0]
securitySchemes:
  oauth_2_0: !include securitySchemes/oauth_2_0.raml
types:
  affiliation_id_only: !include types/affiliation_id_only.json
  affiliation_id: !include types/affiliation_id.json
  affiliation: !include types/affiliation.json
  affiliations_ids: !include types/affiliations_ids.json
  client_id_only: !include types/client_id_only.json
  client_id: !include types/client_id.json
  client: !include types/client.json
  clients_ids: !include types/clients_ids.json
  contacts_ids: !include types/contacts_ids.json
  contact_id_only: !include types/contact_id_only.json
  contact_id: !include types/contact_id.json
  contact: !include types/contact.json
  date_of_engagements_ids: !include types/date_of_engagements_ids.json
  date_of_engagement_id_only: !include types/date_of_engagement_id_only.json
  date_of_engagement_id: !include types/date_of_engagement_id.json
  date_of_engagement: !include types/date_of_engagement.json
  disabilities_ids: !include types/disabilities_ids.json
  disability_id_only: !include types/disability_id_only.json
  disability_id: !include types/disability_id.json
  disability: !include types/disability.json
  domestic_violences_ids: !include types/domestic_violences_ids.json
  domestic_violence_id_only: !include types/domestic_violence_id_only.json
  domestic_violence_id: !include types/domestic_violence_id.json
  domestic_violence: !include types/domestic_violence.json
  education_id_only: !include types/education_id_only.json
  education_id: !include types/education_id.json
  education: !include types/education.json
  educations_ids: !include types/educations_ids.json
  employments_ids: !include types/employments_ids.json
  employment_id_only: !include types/employment_id_only.json
  employment_id: !include types/employment_id.json
  employment: !include types/employment.json
  enrollment_id_only: !include types/enrollment_id_only.json
  enrollment_id: !include types/enrollment_id.json
  enrollment: !include types/enrollment.json
  enrollments_ids: !include types/enrollments_ids.json
  enrollment_coc_id_only: !include types/enrollment_coc_id_only.json
  enrollment_coc_id: !include types/enrollment_coc_id.json
  enrollment_coc: !include types/enrollment_coc.json
  enrollment_cocs_ids: !include types/enrollment_cocs_ids.json
  entry_rhsp_id_only: !include types/entry_rhsp_id_only.json
  entry_rhsp_id: !include types/entry_rhsp_id.json
  entry_rhsp: !include types/entry_rhsp.json
  entry_rhsps_ids: !include types/entry_rhsps_ids.json
  entry_rhy_id_only: !include types/entry_rhy_id_only.json
  entry_rhy_id: !include types/entry_rhy_id.json
  entry_rhy: !include types/entry_rhy.json
  entry_rhys_ids: !include types/entry_rhys_ids.json
  exits_ids: !include types/exits_ids.json
  exit_id_only: !include types/exit_id_only.json
  exit_id: !include types/exit_id.json
  exit: !include types/exit.json
  exit_housing_assessments_ids: !include types/exit_housing_assessments_ids.json
  exit_housing_assessment_id_only: !include types/exit_housing_assessment_id_only.json
  exit_housing_assessment_id: !include types/exit_housing_assessment_id.json
  exit_housing_assessment: !include types/exit_housing_assessment.json
  exit_paths_ids: !include types/exit_paths_ids.json
  exit_path_id_only: !include types/exit_path_id_only.json
  exit_path_id: !include types/exit_path_id.json
  exit_path: !include types/exit_path.json
  exit_rhys_ids: !include types/exit_rhys_ids.json
  exit_rhy_id_only: !include types/exit_rhy_id_only.json
  exit_rhy_id: !include types/exit_rhy_id.json
  exit_rhy: !include types/exit_rhy.json
  funders_ids: !include types/funders_ids.json
  funder_id_only: !include types/funder_id_only.json
  funder_id: !include types/funder_id.json
  funder: !include types/funder.json
  health_insurances_ids: !include types/health_insurances_ids.json
  health_insurance_id_only: !include types/health_insurance_id_only.json
  health_insurance_id: !include types/health_insurance_id.json
  health_insurance: !include types/health_insurance.json
  health_statuses_ids: !include types/health_statuses_ids.json
  health_status_id_only: !include types/health_status_id_only.json
  health_status_id: !include types/health_status_id.json
  health_status: !include types/health_status.json
  housing_assessment_dispositions_ids: !include types/housing_assessment_dispositions_ids.json
  housing_assessment_disposition_id_only: !include types/housing_assessment_disposition_id_only.json
  housing_assessment_disposition_id: !include types/housing_assessment_disposition_id.json
  housing_assessment_disposition: !include types/housing_assessment_disposition.json
  income_and_sources_ids: !include types/income_and_sources_ids.json
  income_and_source_id_only: !include types/income_and_source_id_only.json
  income_and_source_id: !include types/income_and_source_id.json
  income_and_source: !include types/income_and_source.json
  inventories_ids: !include types/inventories_ids.json
  inventory_id_only: !include types/inventory_id_only.json
  inventory_id: !include types/inventory_id.json
  inventory: !include types/inventory.json
  medical_assistances_ids: !include types/medical_assistances_ids.json
  medical_assistance_id_only: !include types/medical_assistance_id_only.json
  medical_assistance_id: !include types/medical_assistance_id.json
  medical_assistance: !include types/medical_assistance.json
  non_cash_benefitses_ids: !include types/non_cash_benefitses_ids.json
  non_cash_benefits_id_only: !include types/non_cash_benefits_id_only.json
  non_cash_benefits_id: !include types/non_cash_benefits_id.json
  non_cash_benefits: !include types/non_cash_benefits.json
  organizations_ids: !include types/organizations_ids.json
  organization_id_only: !include types/organization_id_only.json
  organization_id: !include types/organization_id.json
  organization: !include types/organization.json
  path_statuses_ids: !include types/path_statuses_ids.json
  path_status_id_only: !include types/path_status_id_only.json
  path_status_id: !include types/path_status_id.json
  path_status: !include types/path_status.json
  projects_ids: !include types/projects_ids.json
  project_id_only: !include types/project_id_only.json
  project_id: !include types/project_id.json
  project: !include types/project.json
  project_cocs_ids: !include types/project_cocs_ids.json
  project_coc_id_only: !include types/project_coc_id_only.json
  project_coc_id: !include types/project_coc_id.json
  project_coc: !include types/project_coc.json
  residential_move_in_dates_ids: !include types/residential_move_in_dates_ids.json
  residential_move_in_date_id_only: !include types/residential_move_in_date_id_only.json
  residential_move_in_date_id: !include types/residential_move_in_date_id.json
  residential_move_in_date: !include types/residential_move_in_date.json
  service_fa_referrals_ids: !include types/service_fa_referrals_ids.json
  service_fa_referral_id_only: !include types/service_fa_referral_id_only.json
  service_fa_referral_id: !include types/service_fa_referral_id.json
  service_fa_referral: !include types/service_fa_referral.json
  sites_ids: !include types/sites_ids.json
  site_id_only: !include types/site_id_only.json
  site_id: !include types/site_id.json
  site: !include types/site.json
  veteran_infos_ids: !include types/veteran_infos_ids.json
  veteran_info_id_only: !include types/veteran_info_id_only.json
  veteran_info_id: !include types/veteran_info_id.json
  veteran_info: !include types/veteran_info.json
resourceTypes:
  collection: !include types/collection.raml
  member: !include types/member.raml

/clients:
  type:
    collection:
      schema_ids: clients_ids
      schema_ids_example: !include examples/clients_ids_example.json
      schema: client
      schema_example: !include examples/client_example.json
      schema_id_example: !include examples/client_id_example.json
  /{clientid}:
    type:
       member:
        schema: client
        schema_id: client_id
        schema_id_example: !include examples/client_id_example.json
        schema_example: !include examples/client_example.json
    /enrollments:
      type:
        collection:
          schema_ids: enrollments_ids
          schema_ids_example: !include examples/enrollments_ids_example.json
          schema: enrollment
          schema_example: !include examples/enrollment_example.json
          schema_id_example: !include examples/enrollment_id_example.json
      /{enrollmentid}:
          type:
            member:
              schema: enrollment
              schema_id: enrollment_id
              schema_id_example: !include examples/enrollment_id_example.json
              schema_example: !include examples/enrollment_example.json
          /enrollmentcocs:
            type:
              collection:
                schema_ids: enrollment_cocs_ids
                schema_ids_example: !include examples/enrollment_cocs_ids_example.json
                schema: enrollment_coc
                schema_example: !include examples/enrollment_coc_example.json
                schema_id_example: !include examples/enrollment_coc_id_example.json
            /{enrollmentcocid}:
              type:
                member:
                  schema: enrollment_coc
                  schema_id: enrollment_coc_id
                  schema_id_example: !include examples/enrollment_coc_id_example.json
                  schema_example: !include examples/enrollment_coc_example.json
          /educations:
            type:
              collection:
                schema_ids: educations_ids
                schema_ids_example: !include examples/educations_ids_example.json
                schema: education
                schema_example: !include examples/education_example.json
                schema_id_example: !include examples/education_id_example.json
            /{educationid}:
              type:
                member:
                  schema: education
                  schema_id: education_id
                  schema_id_example: !include examples/education_id_example.json
                  schema_example: !include examples/education_example.json
          /contacts:
            type:
              collection:
                schema_ids: contacts_ids
                schema_ids_example: !include examples/contacts_ids_example.json
                schema: contact
                schema_example: !include examples/contact_example.json
                schema_id_example: !include examples/contact_id_example.json
            /{contactid}:
              type:
                member:
                  schema: contact
                  schema_id: contact_id
                  schema_id_example: !include examples/contact_id_example.json
                  schema_example: !include examples/contact_example.json
          /dateofengagements:
            type:
              collection:
                schema_ids: date_of_engagements_ids
                schema_ids_example: !include examples/date_of_engagements_ids_example.json
                schema: date_of_engagement
                schema_example: !include examples/date_of_engagement_example.json
                schema_id_example: !include examples/date_of_engagement_id_example.json
            /{dateofengagementid}:
              type:
                member:
                  schema: date_of_engagement
                  schema_id: date_of_engagement_id
                  schema_id_example: !include examples/date_of_engagement_id_example.json
                  schema_example: !include examples/date_of_engagement_example.json
          /disabilities:
            type:
              collection:
                schema_ids: disabilities_ids
                schema_ids_example: !include examples/disabilities_ids_example.json
                schema: disability
                schema_example: !include examples/disability_example.json
                schema_id_example: !include examples/disability_id_example.json
            /{disabilityid}:
              type:
                member:
                  schema: disability
                  schema_id: disability_id
                  schema_id_example: !include examples/disability_id_example.json
                  schema_example: !include examples/disability_example.json
          /domesticviolences:
            type:
              collection:
                schema_ids: domestic_violences_ids
                schema_ids_example: !include examples/domestic_violences_ids_example.json
                schema: domestic_violence
                schema_example: !include examples/domestic_violence_example.json
                schema_id_example: !include examples/domestic_violence_id_example.json
            /{domesticviolenceid}:
              type:
                member:
                  schema: domestic_violence
                  schema_id: domestic_violence_id
                  schema_id_example: !include examples/domestic_violence_id_example.json
                  schema_example: !include examples/domestic_violence_example.json
          /employments:
            type:
              collection:
                schema_ids: employments_ids
                schema_ids_example: !include examples/employments_ids_example.json
                schema: employment
                schema_example: !include examples/employment_example.json
                schema_id_example: !include examples/employment_id_example.json
            /{employmentid}:
              type:
                member:
                  schema: employment
                  schema_id: employment_id
                  schema_id_example: !include examples/employment_id_example.json
                  schema_example: !include examples/employment_example.json
          /healthinsurances:
            type:
              collection:
                schema_ids: health_insurances_ids
                schema_ids_example: !include examples/health_insurances_ids_example.json
                schema: health_insurance
                schema_example: !include examples/health_insurance_example.json
                schema_id_example: !include examples/health_insurance_id_example.json
            /{healthinsuranceid}:
              type:
                member:
                  schema: health_insurance
                  schema_id: health_insurance_id
                  schema_id_example: !include examples/health_insurance_id_example.json
                  schema_example: !include examples/health_insurance_example.json
          /healthstatuses:
            type:
              collection:
                schema_ids: health_statuses_ids
                schema_ids_example: !include examples/health_statuses_ids_example.json
                schema: health_status
                schema_example: !include examples/health_status_example.json
                schema_id_example: !include examples/health_status_id_example.json
            /{healthstatusid}:
              type:
                member:
                  schema: health_status
                  schema_id: health_status_id
                  schema_id_example: !include examples/health_status_id_example.json
                  schema_example: !include examples/health_status_example.json
          /incomeandsources:
            type:
              collection:
                schema_ids: income_and_sources_ids
                schema_ids_example: !include examples/income_and_sources_ids_example.json
                schema: income_and_source
                schema_example: !include examples/income_and_source_example.json
                schema_id_example: !include examples/income_and_source_id_example.json
            /{incomeandsourceid}:
              type:
                member:
                  schema: income_and_source
                  schema_id: income_and_source_id
                  schema_id_example: !include examples/income_and_source_id_example.json
                  schema_example: !include examples/income_and_source_example.json
          /medicalassistances:
            type:
              collection:
                schema_ids: medical_assistances_ids
                schema_ids_example: !include examples/medical_assistances_ids_example.json
                schema: medical_assistance
                schema_example: !include examples/medical_assistance_example.json
                schema_id_example: !include examples/medical_assistance_id_example.json
            /{medicalassistanceid}:
              type:
                member:
                  schema: medical_assistance
                  schema_id: medical_assistance_id
                  schema_id_example: !include examples/medical_assistance_id_example.json
                  schema_example: !include examples/medical_assistance_example.json
          /noncashbenefits:
            type:
              collection:
                schema_ids: non_cash_benefitses_ids
                schema_ids_example: !include examples/non_cash_benefitses_ids_example.json
                schema: non_cash_benefits
                schema_example: !include examples/non_cash_benefits_example.json
                schema_id_example: !include examples/non_cash_benefits_id_example.json
            /{noncashbenefitid}:
              type:
                member:
                  schema: non_cash_benefits
                  schema_id: non_cash_benefits_id
                  schema_id_example: !include examples/non_cash_benefits_id_example.json
                  schema_example: !include examples/non_cash_benefits_example.json
          /residentialmoveindates:
            type:
              collection:
                schema_ids: residential_move_in_dates_ids
                schema_ids_example: !include examples/residential_move_in_dates_ids_example.json
                schema: residential_move_in_date
                schema_example: !include examples/residential_move_in_date_example.json
                schema_id_example: !include examples/residential_move_in_date_id_example.json
            /{residentialmoveindateid}:
              type:
                member:
                  schema: residential_move_in_date
                  schema_id: residential_move_in_date_id
                  schema_id_example: !include examples/residential_move_in_date_id_example.json
                  schema_example: !include examples/residential_move_in_date_example.json
          /pathstatuses:
            type:
              collection:
                schema_ids: path_statuses_ids
                schema_ids_example: !include examples/path_statuses_ids_example.json
                schema: path_status
                schema_example: !include examples/path_status_example.json
                schema_id_example: !include examples/path_status_id_example.json
            /{pathstatusid}:
              type:
                member:
                  schema: path_status
                  schema_id: path_status_id
                  schema_id_example: !include examples/path_status_id_example.json
                  schema_example: !include examples/path_status_example.json
          /entryrhsps:
            type:
              collection:
                schema_ids: entry_rhsps_ids
                schema_ids_example: !include examples/entry_rhsps_ids_example.json
                schema: entry_rhsp
                schema_example: !include examples/entry_rhsp_example.json
                schema_id_example: !include examples/entry_rhsp_id_example.json
            /{entryrhspid}:
              type:
                member:
                  schema: entry_rhsp
                  schema_id: entry_rhsp_id
                  schema_id_example: !include examples/entry_rhsp_id_example.json
                  schema_example: !include examples/entry_rhsp_example.json
          /entryrhys:
            type:
              collection:
                schema_ids: entry_rhys_ids
                schema_ids_example: !include examples/entry_rhys_ids_example.json
                schema: entry_rhy
                schema_example: !include examples/entry_rhy_example.json
                schema_id_example: !include examples/entry_rhy_id_example.json
            /{entryrhyid}:
              type:
                member:
                  schema: entry_rhy
                  schema_id: entry_rhy_id
                  schema_id_example: !include examples/entry_rhy_id_example.json
                  schema_example: !include examples/entry_rhy_example.json
          /entryssvfs:
            type:
              collection:
                schema_ids: educations_ids
                schema_ids_example: !include examples/educations_ids_example.json
                schema: education
                schema_example: !include examples/education_example.json
                schema_id_example: !include examples/education_id_example.json
            /{entryssvfid}:
              type:
                member:
                  schema: education
                  schema_id: education_id
                  schema_id_example: !include examples/education_id_example.json
                  schema_example: !include examples/education_example.json
          /servicefareferrals:
            type:
              collection:
                schema_ids: educations_ids
                schema_ids_example: !include examples/educations_ids_example.json
                schema: education
                schema_example: !include examples/education_example.json
                schema_id_example: !include examples/education_id_example.json
            /{servicefareferralid}:
              type:
                member:
                  schema: education
                  schema_id: education_id
                  schema_id_example: !include examples/education_id_example.json
                  schema_example: !include examples/education_example.json
          /veteraninfos:
            type:
              collection:
                schema_ids: veteran_infos_ids
                schema_ids_example: !include examples/veteran_infos_ids_example.json
                schema: veteran_info
                schema_example: !include examples/veteran_info_example.json
                schema_id_example: !include examples/veteran_info_id_example.json
            /{veteraninfoid}:
              type:
                member:
                  schema: veteran_info
                  schema_id: veteran_info_id
                  schema_id_example: !include examples/veteran_info_id_example.json
                  schema_example: !include examples/veteran_info_example.json
          /exits:
            type:
              collection:
                schema_ids: exits_ids
                schema_ids_example: !include examples/exits_ids_example.json
                schema: exit
                schema_example: !include examples/exit_example.json
                schema_id_example: !include examples/exit_id_example.json
            /{exitid}:
              type:
                member:
                  schema: exit
                  schema_id: exit_id
                  schema_id_example: !include examples/exit_id_example.json
                  schema_example: !include examples/exit_example.json
              /exithousingassesments:
                type:
                  collection:
                    schema_ids: exit_housing_assessments_ids
                    schema_ids_example: !include examples/exit_housing_assessments_ids_example.json
                    schema: exit_housing_assessment
                    schema_example: !include examples/exit_housing_assessment_example.json
                    schema_id_example: !include examples/exit_housing_assessment_id_example.json
                /{exithousingassesmentid}:
                  type:
                    member:
                      schema: exit_housing_assessment
                      schema_id: exit_housing_assessment_id
                      schema_id_example: !include examples/exit_housing_assessment_id_example.json
                      schema_example: !include examples/exit_housing_assessment_example.json
              /housingassessmentdispositions:
                type:
                  collection:
                    schema_ids: housing_assessment_dispositions_ids
                    schema_ids_example: !include examples/housing_assessment_dispositions_ids_example.json
                    schema: housing_assessment_disposition
                    schema_example: !include examples/housing_assessment_disposition_example.json
                    schema_id_example: !include examples/housing_assessment_disposition_id_example.json
                /{housingassessmentdispositionid}:
                  type:
                    member:
                      schema: housing_assessment_disposition
                      schema_id: housing_assessment_disposition_id
                      schema_id_example: !include examples/housing_assessment_disposition_id_example.json
                      schema_example: !include examples/housing_assessment_disposition_example.json
              /exitpaths:
                type:
                  collection:
                    schema_ids: exit_paths_ids
                    schema_ids_example: !include examples/exit_paths_ids_example.json
                    schema: exit_path
                    schema_example: !include examples/exit_path_example.json
                    schema_id_example: !include examples/exit_path_id_example.json
                /{exitpathid}:
                  type:
                    member:
                      schema: exit_path
                      schema_id: exit_path_id
                      schema_id_example: !include examples/exit_path_id_example.json
                      schema_example: !include examples/exit_path_example.json
              /exitrhys:
                type:
                  collection:
                    schema_ids: exit_rhys_ids
                    schema_ids_example: !include examples/exit_rhys_ids_example.json
                    schema: exit_rhy
                    schema_example: !include examples/exit_rhy_example.json
                    schema_id_example: !include examples/exit_rhy_id_example.json
                /{exitrhyid}:
                  type:
                    member:
                      schema: exit_rhy
                      schema_id: exit_rhy_id
                      schema_id_example: !include examples/exit_rhy_id_example.json
                      schema_example: !include examples/exit_rhy_example.json
/projects:
  type:
    collection:
      schema_ids: projects_ids
      schema_ids_example: !include examples/projects_ids_example.json
      schema: project
      schema_example: !include examples/project_example.json
      schema_id_example: !include examples/project_id_example.json
  /{projectid}:
    type:
      member:
        schema: project
        schema_id: project_id
        schema_id_example: !include examples/project_id_example.json
        schema_example: !include examples/project_example.json
  /projectcocs:
    type:
      collection:
        schema_ids: project_cocs_ids
        schema_ids_example: !include examples/project_cocs_ids_example.json
        schema: project_coc
        schema_example: !include examples/project_coc_example.json
        schema_id_example: !include examples/project_coc_id_example.json
    /{projectcocid}:
          type:
            member:
              schema: project_coc
              schema_id: project_coc_id
              schema_id_example: !include examples/project_coc_id_example.json
              schema_example: !include examples/project_coc_example.json
  /inventories:
    type:
      collection:
        schema_ids: inventories_ids
        schema_ids_example: !include examples/inventories_ids_example.json
        schema: inventory
        schema_example: !include examples/inventory_example.json
        schema_id_example: !include examples/inventory_id_example.json
    /{inventoryid}:
      type:
        member:
          schema: inventory
          schema_id: inventory_id
          schema_id_example: !include examples/inventory_id_example.json
          schema_example: !include examples/inventory_example.json
  /sites:
    type:
      collection:
        schema_ids: sites_ids
        schema_ids_example: !include examples/sites_ids_example.json
        schema: site
        schema_example: !include examples/site_example.json
        schema_id_example: !include examples/site_id_example.json
    /{siteid}:
      type:
        member:
          schema: site
          schema_id: site_id
          schema_id_example: !include examples/site_id_example.json
          schema_example: !include examples/site_example.json
  /funders:
    type:
      collection:
        schema_ids: funders_ids
        schema_ids_example: !include examples/funders_ids_example.json
        schema: funder
        schema_example: !include examples/funder_example.json
        schema_id_example: !include examples/funder_id_example.json
    /{funderid}:
      type:
        member:
          schema: funder
          schema_id: funder_id
          schema_id_example: !include examples/funder_id_example.json
          schema_example: !include examples/funder_example.json
  /affiliations:
    type:
      collection:
        schema_ids: affiliations_ids
        schema_ids_example: !include examples/affiliations_ids_example.json
        schema: affiliation
        schema_example: !include examples/affiliation_example.json
        schema_id_example: !include examples/affiliation_id_example.json
    /{affiliationid}:
      type:
        member:
          schema: affiliation
          schema_id: affiliation_id
          schema_id_example: !include examples/affiliation_id_example.json
          schema_example: !include examples/affiliation_example.json
/organizations:
  type:
    collection:
      schema_ids: organizations_ids
      schema_ids_example: !include examples/organizations_ids_example.json
      schema: organization
      schema_example: !include examples/organization_example.json
      schema_id_example: !include examples/organization_id_example.json
  /{organizationid}:
    type:
      member:
        schema: organization
        schema_id: organization_id
        schema_id_example: !include examples/organization_id_example.json
        schema_example: !include examples/organization_example.json
/search:
  '/{searchentity}':
    get:
      description: |
        The Search API is optimized to find the specific entity you're looking for (e.g., a client, enrollments, etc.).It's designed to  find the one result you're looking for (or maybe the few results you're looking for). Currently hmislynk supporting search on 'clients' entity only. Just like searching on Google, you sometimes want to see a few pages of search results so that you can find the item that best meets your needs.  HMISLynk Search API provides up to 50 results for each searh. However, the search results can be limited by the client. Note: Current supporting URI  is /search/clients

      responses:
        '200':
          description: |
            example: |
              {
              "searchResults": {
                "pagination": {
                  "total":"2"
                  "from": "0",
                  "maximum": "50",
                  "returned":"2"
                },
                "items": [
                  {
                    "clientId": "65e3df62-dd22-4d07-83ef-6858a6322839",
                    "firstName": "Eric",
                    "middleName": "Eric",
                    "lastName": "Eric",
                    "nameSuffix": "NS ",
                    "nameDataQuality": "1",
                    "ssn": "ssn ",
                    "ssnDataQuality": "1",
                    "dob": "1459498034983",
                    "dobDataQuality": "1",
                    "race": "1",
                    "ethnicity": "1",
                    "gender": "1",
                    "otherGender": "Test",
                    "veteranStatus": "8",
                    "link":"/hmis-clientapi/rest/v2015/clients/65e3df62-dd22-4d07-83ef-6858a6322839"
                  },
                  {
                    "clientId": "cf98b9b2-9a77-4133-99a3-b60f05a12ad1",
                    "firstName": "Eric",
                    "middleName": "Eric",
                    "lastName": "Eric",
                    "nameSuffix": "NS ",
                    "nameDataQuality": "1",
                    "ssn": "ssn ",
                    "ssnDataQuality": "1",
                    "dob": "1459498034983",
                    "dobDataQuality": "1",
                    "race": "1",
                    "ethnicity": "1",
                    "gender": "1",
                    "otherGender": "Test",
                    "veteranStatus": "8",
                    "link":"/hmis-clientapi/rest/v2014/clients/cf98b9b2-9a77-4133-99a3-b60f05a12ad1"
                  }
                ]
              }
              }

      queryParameters:
        q:
          description: |
            The search keywords, as well as any qualifiers. Currently supported search fields are first name,middle name,last name,dob,source system id and ssn. For search on "date of birth" field the format MM-dd-YYYY should be used for the search keyword.
        sort:
          description: The sort field. Default- results are sorted by "created date".
          example: created date
          type: string
        order:
          description: The sort order if sort parameter is provided. One of asc or desc. Default- desc.
          example: desc
          default: desc
          type: string
        startIndex:
          description: The start Index from where the search results should be returned. Default - 0
          example: 0
          default: 0
          type: integer
        maxItems:
          description: the number or Items that should be included in the results . Default - 50
          example: 50
          default: 50
          type: integer
        exclude:
          description: |
            Excludes flieds from the search.Currently it suppoted value is "ssi" (to exclude         source system id) only.
    uriParameters:
      searchentity: {}
/dataelements:
  description: Get all available data elements
  get:
    responses:
      200:
        body:
          application/json:
             example: !include examples/get_all_hmis_type_names.json
             schema: !include types/get_all_hmis_type_names.json
  /{name}/values:
    description:  get all values of elements
    get:
      responses:
        200:
          body:
            application/json:
              example: !include examples/get_all_hmis_type_value_of_hmis_type.json
              schema: !include types/get_all_hmis_type_value_of_hmis_type.json

/questions:
  description:  get all HUD Questions. Maximum number items (questions) that can be returned in a response is 200.
  get:
    queryParameters:
     text:
      description: filter on actual question text ( displayText )
      required: false
    responses:
      200:
        body:
          application/json:
            example: !include examples/get_all_survey_questions.json
            schema: !include types/get_all_survey_questions.json
/questions/{hudQuestionId}:
  description:  get HUD Question by hudQuestionId
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/get_survey_question_by_hudid.json
            schema: !include types/get_survey_question_by_hudid.json
